// The two hand-rolled primitives, pinned against the platform implementations
// they replaced -- docs/research/apkg-format.md §2 (crc32) and §6 (sha1).
//
// Why this file exists at all. Both were written because a browser has
// neither node:crypto nor node:zlib, and both are the kind of code that is
// either exactly right or silently, unfixably wrong. Before this, neither had
// a test:
//
//   * crc32 was covered only incidentally, through one hardcoded CRC for a
//     108-byte fixture in zip.test.ts and `unzip -t`. Its own header claimed
//     a differential test against node:zlib that did not exist anywhere.
//   * sha1 was worse. Its only caller, fieldChecksum (src/apkg/text.ts), reads
//     `getUint32(0)` -- the first four bytes -- so the four `csum` values
//     pinned in notes.test.ts observed h0 and nothing else. A bug confined to
//     h1..h4 would have shipped green through the entire suite.
//
// So this asserts all 20 digest bytes, and sweeps the block boundaries where
// hand-rolled SHA-1 padding usually breaks (55/56/57 and 63/64/65 are where
// the extra block appears).
//
// Inputs are generated by a fixed LCG rather than randomBytes: a differential
// test that fails on unseeded input cannot be re-run against the same case.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { crc32 as zlibCrc32 } from 'node:zlib';

import { sha1 } from '../../dist/apkg/sha1.js';
import { crc32 } from '../../dist/apkg/crc32.js';

/** Deterministic bytes: a plain 32-bit LCG, so a failure is reproducible. */
function bytes(length: number, seed = 1): Uint8Array {
  const out = new Uint8Array(length);
  let state = seed >>> 0;
  for (let i = 0; i < length; i += 1) {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    out[i] = (state >>> 24) & 0xff;
  }
  return out;
}

/** 0-130 covers every padding boundary; the rest are multi-block and long. */
const LENGTHS = [...Array(131).keys(), 255, 256, 257, 1023, 1024, 4096];

const hex = (u8: Uint8Array): string => Buffer.from(u8).toString('hex');

test('sha1 matches node:crypto across every block boundary, all 20 bytes', () => {
  for (const length of LENGTHS) {
    const input = bytes(length);
    assert.equal(
      hex(sha1(input)),
      createHash('sha1').update(input).digest('hex'),
      `sha1 mismatch at length ${length}`,
    );
  }
});

test('sha1 matches the published FIPS 180-4 vectors', () => {
  const utf8 = new TextEncoder();
  assert.equal(hex(sha1(utf8.encode('abc'))), 'a9993e364706816aba3e25717850c26c9cd0d89d');
  assert.equal(hex(sha1(utf8.encode(''))), 'da39a3ee5e6b4b0d3255bfef95601890afd80709');
  assert.equal(
    hex(sha1(utf8.encode('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq'))),
    '84983e441c3bd26ebaae4aa1f95129e5e54670f1',
  );
});

test('sha1 matches node:crypto on multi-byte UTF-8, as fieldChecksum feeds it', () => {
  const utf8 = new TextEncoder();
  for (const text of ['Osteoid', 'café ☕ naïve', '細胞核', 'échographie', 'é'.repeat(500)]) {
    assert.equal(
      hex(sha1(utf8.encode(text))),
      createHash('sha1').update(text, 'utf8').digest('hex'),
      `sha1 mismatch for ${JSON.stringify(text.slice(0, 20))}`,
    );
  }
});

test('sha1 reads a subarray by its own bounds, not the whole backing buffer', () => {
  // The digest is fed views elsewhere in the writer; a `.buffer` bug here
  // would hash neighbouring bytes and still look plausible.
  const backing = bytes(200, 7);
  const view = backing.subarray(3, 61);
  assert.equal(hex(sha1(view)), createHash('sha1').update(view).digest('hex'));
});

test('crc32 matches node:zlib across the same corpus', () => {
  for (const length of LENGTHS) {
    const input = bytes(length, 2);
    assert.equal(
      crc32(input),
      zlibCrc32(Buffer.from(input)) >>> 0,
      `crc32 mismatch at length ${length}`,
    );
  }
});

test('crc32 matches the published check value and is unsigned', () => {
  assert.equal(crc32(new TextEncoder().encode('123456789')), 0xcbf43926);
  assert.equal(crc32(new Uint8Array(0)), 0);
  // Every ZIP header writes this through DataView.setUint32, which would
  // silently wrap a negative accumulator.
  for (const length of [1, 17, 64, 255]) {
    const value = crc32(bytes(length, 3));
    assert.ok(value >= 0 && value <= 0xffffffff, `crc32 out of uint32 range: ${value}`);
  }
});
