// Plumbing for test/sidecar/agent-*.test.ts -- the ACP half of
// docs/research/agent-protocol.md (§2, §3, §5 bullets 3-4), written by a
// context that has not seen src/sidecar/agent*.ts, src/agents/ or
// src/agent/. Builds on ./helpers.ts (spawn, request, captured stdout
// lines) and adds what the reverse direction needs: answering a request the
// sidecar sends us, and waiting for a notification by predicate.
//
// The provider under test is laid out BY HAND as an installed npx package
// (§1's prefix layout: <dataDir>/npx/mock/node_modules/mock-agent/), whose
// bin is a shim that runs test/acp/mock-agent.ts in-process (same pid, so
// ACP_TEST_PIDFILE names the sidecar's direct child and reaping can be
// asserted the way test/acp/lifecycle.test.ts does). Invoked with the Claude
// login args (claude-adapter-auth.md §2/§4) the shim instead prints two
// lines and exits 0, touching a marker file that makes the NEXT run report
// itself signed in -- the "fake login script" §5 bullet 4 calls for.
//
// The registry cache is primed through `agents/list` against a one-shot
// local fake (node:http), so <dataDir>/registry.json is fresh and in the
// sidecar's own format without a byte of network; a hand-laid copy with an
// ISO `fetchedAt` is written first so an implementation that already reads
// that shape never fetches at all.
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createServer } from 'node:http';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { pidIsAlive, waitForExit } from '../acp/helpers.ts';
import type { ScenarioName } from '../acp/scenarios.ts';
import { makeTmpDir, withTimeout, type RpcError, type RpcMessage, type Sidecar } from './helpers.ts';

export { pidIsAlive, waitForExit };

export const MOCK_AGENT_PATH = fileURLToPath(new URL('../acp/mock-agent.ts', import.meta.url));
export const MOCK_PROVIDER_ID = 'mock';
export const MOCK_PACKAGE = 'mock-agent';
export const MOCK_VERSION = '0.0.1';
export const DEFAULT_REGISTRY_URL = 'https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json';
/** The registry entry (agent-install-and-auth.md §3 shape) `agent/connect { provider: "mock" }` resolves through. */
export const MOCK_REGISTRY_ENTRY = {
  id: MOCK_PROVIDER_ID,
  name: 'Mock',
  description: '',
  version: MOCK_VERSION,
  distribution: { npx: { package: MOCK_PACKAGE, args: [] as string[] } },
};
/** What the shim prints on a login run, in order (claude-adapter-auth.md §4's two lines, shapes only). */
export const LOGIN_STDOUT_LINES = [
  'Opening browser to sign in…',
  'https://claude.com/cai/oauth/authorize?redirect_uri=http://localhost:0/callback&scope=test',
];
export const CLAUDE_LOGIN_ARGS = ['--cli', 'auth', 'login', '--claudeai'];
/** The `_auth/status_update` the shim makes the mock send once the marker exists. */
export const LOGGED_IN_STATUS = { kind: 'claude', label: 'Logged in' };

// ---- §2 result shapes, transcribed for typing only -----------------------

export interface AuthStatus { kind: string; label: string }
export interface ConnectSession {
  sessionId: string;
  modes: { currentModeId: string; availableModes: Array<{ id: string; name: string; description?: string }> } | null;
  configOptions: Array<Record<string, unknown>> | null;
  commands: unknown[];
}
export interface ConnectResult {
  connectionId: string;
  provider: string;
  kind: 'acp' | 'api';
  agent: { name: string; version: string } | null;
  authStatus: AuthStatus | null;
  authMethods: Array<Record<string, unknown>>;
  session: ConnectSession | null;
  authRequired: boolean;
}
export interface StatusResult {
  connectionId: string;
  provider: string;
  kind: string;
  authStatus: AuthStatus | null;
  authMethods: unknown[];
  sessions: string[];
}
export interface LoginResult {
  methodId: string;
  exitCode: number | null;
  authenticated: boolean;
  session?: ConnectSession | null;
}

// ---- the installed-package layout ----------------------------------------

function shimSource(): string {
  const mockUrl = pathToFileURL(MOCK_AGENT_PATH).href;
  return `#!/usr/bin/env node
// Generated by test/sidecar/agent-helpers.ts: the bin of the hand-laid "mock-agent" package.
import { appendFileSync, existsSync, writeFileSync } from 'node:fs';
const argv = process.argv.slice(2);
if (process.env.APE_MOCK_ARGV_FILE) appendFileSync(process.env.APE_MOCK_ARGV_FILE, JSON.stringify(argv) + '\\n');
if (argv.includes('--cli')) {
  // A login run (claude-adapter-auth.md §4): two lines, exit 0, and the next
  // agent run reports itself signed in. exitCode (not process.exit) so a
  // pipe-backed stdout is flushed before the process ends.
  if (process.env.APE_MOCK_LOGIN_MARKER) writeFileSync(process.env.APE_MOCK_LOGIN_MARKER, 'logged-in\\n');
  process.stdout.write(${JSON.stringify(LOGIN_STDOUT_LINES.map((l) => `${l}\n`).join(''))});
  process.exitCode = 0;
} else {
  if (process.env.APE_MOCK_LOGIN_MARKER && existsSync(process.env.APE_MOCK_LOGIN_MARKER)) {
    process.env.ACP_MOCK_AUTH_STATUS = ${JSON.stringify(JSON.stringify(LOGGED_IN_STATUS))};
  }
  process.argv.splice(2, 0, '--scenario=' + (process.env.APE_MOCK_SCENARIO ?? ''));
  await import(${JSON.stringify(mockUrl)});
}
`;
}

/**
 * A fresh dataDir holding the mock provider "installed" per §1's layout,
 * plus a registry cache naming it. `installed: false` lays out the cache
 * only, for the "-32000 not installed" path.
 */
export function layoutMockProvider(opts: { installed?: boolean } = {}): { dataDir: string; bin: string } {
  const dataDir = makeTmpDir('ape-sidecar-agent-');
  const pkgDir = join(dataDir, 'npx', MOCK_PROVIDER_ID, 'node_modules', MOCK_PACKAGE);
  const bin = join(pkgDir, 'index.js');
  if (opts.installed !== false) {
    mkdirSync(pkgDir, { recursive: true });
    writeFileSync(join(pkgDir, 'package.json'), `${JSON.stringify({ name: MOCK_PACKAGE, version: MOCK_VERSION, type: 'module', bin: { [MOCK_PACKAGE]: 'index.js' } }, null, 2)}\n`);
    writeFileSync(bin, shimSource());
  }
  writeFileSync(join(dataDir, 'registry.json'), `${JSON.stringify({
    fetchedAt: new Date().toISOString(),
    url: DEFAULT_REGISTRY_URL,
    version: '1.0.0',
    agents: [MOCK_REGISTRY_ENTRY],
    extensions: [],
  }, null, 2)}\n`);
  return { dataDir, bin };
}

/**
 * Primes <dataDir>/registry.json through `agents/list` against a one-shot
 * local registry serving only the mock entry, so the cache is fresh and in
 * whatever shape the sidecar writes. Asserts the provider is listed.
 */
export async function primeRegistry(s: Sidecar, dataDir: string, expectInstalled = true): Promise<void> {
  const server = createServer((req, res) => {
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ version: '1.0.0', agents: [MOCK_REGISTRY_ENTRY], extensions: [] }));
  });
  const url = await new Promise<string>((resolve, reject) => {
    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const addr = server.address();
      if (!addr || typeof addr === 'string') { reject(new Error('fake registry: no port')); return; }
      resolve(`http://127.0.0.1:${addr.port}/registry.json`);
    });
  });
  try {
    const res = await s.request('prime-registry', 'agents/list', { dataDir, registryUrl: url, refresh: true });
    assert.equal(res.error, undefined, `agents/list while priming: ${JSON.stringify(res.error)}`);
    const providers = (res.result as { providers: Array<{ id: string; installed: boolean; installedVersion: string | null }> }).providers;
    const mock = providers.find((p) => p.id === MOCK_PROVIDER_ID);
    assert.ok(mock, `the mock entry must be listed: ${JSON.stringify(providers)}`);
    assert.equal(mock.installed, expectInstalled, 'installed is read from the hand-laid prefix');
    if (expectInstalled) assert.equal(mock.installedVersion, MOCK_VERSION);
  } finally {
    await new Promise<void>((done) => { server.closeAllConnections(); server.close(() => done()); });
  }
}

/** The per-connection files the shim and the mock write; one set per agent process. */
export interface MockFiles { dir: string; logFile: string; pidFile: string; argvFile: string; marker: string; env: Record<string, string> }
export function mockFiles(scenario: ScenarioName): MockFiles {
  const dir = makeTmpDir('ape-sidecar-mock-');
  const logFile = join(dir, 'mock.log');
  const pidFile = join(dir, 'agent.pid');
  const argvFile = join(dir, 'argv.log');
  const marker = join(dir, 'logged-in');
  return {
    dir, logFile, pidFile, argvFile, marker,
    env: { ACP_MOCK_LOG: logFile, ACP_TEST_PIDFILE: pidFile, APE_MOCK_ARGV_FILE: argvFile, APE_MOCK_LOGIN_MARKER: marker, APE_MOCK_SCENARIO: scenario },
  };
}

let connectSeq = 0;
/** `agent/connect { provider: "mock" }` with the scenario chosen via env; asserts success and returns the typed result. */
export async function connectMock(
  s: Sidecar,
  dataDir: string,
  scenario: ScenarioName,
  opts: { cwd?: string; extraArgs?: string[] } = {},
): Promise<{ result: ConnectResult; files: MockFiles; id: string }> {
  const files = mockFiles(scenario);
  const id = `connect-${++connectSeq}`;
  const params: Record<string, unknown> = { provider: MOCK_PROVIDER_ID, dataDir, cwd: opts.cwd ?? dataDir, env: files.env };
  if (opts.extraArgs) params.extraArgs = opts.extraArgs;
  const res = await s.request(id, 'agent/connect', params);
  assert.equal(res.error, undefined, `agent/connect (${scenario}): ${JSON.stringify(res.error)}`);
  return { result: res.result as ConnectResult, files, id };
}

// ---- the reverse direction and notifications ------------------------------

/** Answers a request the sidecar sent us (§3 `agent/requestPermission`) with a result. */
export function answerRequest(s: Sidecar, id: string | number, result: unknown): Promise<void> {
  return s.writeRaw(`${JSON.stringify({ jsonrpc: '2.0', id, result })}\n`);
}
/** Answers a sidecar-sent request with an error response instead. */
export function answerError(s: Sidecar, id: string | number, error: RpcError): Promise<void> {
  return s.writeRaw(`${JSON.stringify({ jsonrpc: '2.0', id, error })}\n`);
}

/** Resolves with the first captured stdout message at index >= `from` matching `pred`, waiting for more lines as needed. */
export function waitForLine(s: Sidecar, pred: (m: RpcMessage) => boolean, label: string, from = 0): Promise<{ msg: RpcMessage; index: number }> {
  return withTimeout((async () => {
    let i = from;
    for (;;) {
      for (; i < s.lines.length; i++) {
        const j = s.lines[i].json;
        if (j && pred(j)) return { msg: j, index: i };
      }
      await s.waitForLines(s.lines.length + 1);
    }
  })(), label);
}
export function isNotification(m: RpcMessage, method: string): boolean {
  return m.method === method && !('id' in m);
}
/** params of every notification `method` captured so far, in order. */
export function notificationParams<T = Record<string, unknown>>(s: Sidecar, method: string, from = 0): T[] {
  return s.lines.slice(from).filter((l) => l.json && isNotification(l.json, method)).map((l) => l.json!.params as T);
}
export function updatesFor(s: Sidecar, sessionId: string, from = 0): Array<Record<string, unknown>> {
  return notificationParams<{ sessionId: string; update: Record<string, unknown> }>(s, 'agent/update', from)
    .filter((p) => p.sessionId === sessionId)
    .map((p) => p.update);
}

// ---- the mock's own log (test/acp/mock-agent.ts's {dir, raw, t} lines) ----

export interface Frame { method?: string; id?: unknown; params?: Record<string, unknown>; result?: unknown; error?: RpcError }
export function readMockLog(logFile: string, dir: 'recv' | 'send'): Frame[] {
  if (!existsSync(logFile)) return [];
  return readFileSync(logFile, 'utf8')
    .split('\n')
    .filter((l) => l.length > 0)
    .map((l) => JSON.parse(l) as { dir: 'send' | 'recv'; raw: string })
    .filter((e) => e.dir === dir)
    .map((e) => JSON.parse(e.raw) as Frame);
}
/** What the sidecar (as ACP client) sent the agent, in order. */
export const agentReceived = (logFile: string): Frame[] => readMockLog(logFile, 'recv');
/** The agent's own session ids, from its session/new results, in order. */
export function agentSessionIds(logFile: string): string[] {
  return readMockLog(logFile, 'send')
    .map((f) => (f.result as { sessionId?: unknown } | undefined)?.sessionId)
    .filter((v): v is string => typeof v === 'string');
}
export function agentPid(pidFile: string): number {
  const pid = Number(readFileSync(pidFile, 'utf8').trim());
  assert.ok(Number.isFinite(pid) && pid > 0, `pidfile ${pidFile} holds ${JSON.stringify(readFileSync(pidFile, 'utf8'))}`);
  return pid;
}
/** Each shim invocation's argv (after the bin), one per line, in order. */
export function shimArgvs(argvFile: string): string[][] {
  if (!existsSync(argvFile)) return [];
  return readFileSync(argvFile, 'utf8').split('\n').filter((l) => l.length > 0).map((l) => JSON.parse(l) as string[]);
}

export function expectError(res: RpcMessage, code: number, label: string): RpcError {
  assert.ok(res.error, `${label}: expected an error response, got ${JSON.stringify(res)}`);
  assert.ok(!('result' in res), `${label}: an error response carries no result`);
  assert.equal(res.error.code, code, `${label}: ${res.error.message}`);
  assert.ok(res.error.message.length > 0, `${label}: message must be human-readable`);
  return res.error;
}
